### ISSUE TITLE
Prismatic mine crash

### ISSUE THREAD

**Issue by QmelZ** [Pyratite/pixelcraft#24]
**Describe the bug**

crash

**To Reproduce**

1. put down ~~gay~~ prismatic mine
2. become crux
3. hit the mine
4. experience the  ***c r a s h***

**Expected behavior**

the mine takes damage

**Screenshots**

![image](https://user-images.githubusercontent.com/59574967/102472951-e4d67080-4067-11eb-9d30-0dfe39b416c6.png)

**Info**
Version of the mod you are running: 0.9.5
Version of Mindustry you are running: 121.2

**Additional context**

[crash-report-12_17_2020_12_58_27.txt](https://github.com/Sh1penfire/pixelcraft/files/5708470/crash-report-12_17_2020_12_58_27.txt)
only testing utilities and pixelcraft was enabled

* [X] I have checked this issue doesn't already exist.
* [X] This is a bug and not a feature request.
[X] This is an x in a box

**Comment by Sh1penfire** [comment]
I'll go check out what happens when it takes damage and see how to fix this
