### ISSUE TITLE
Second planet is missing

### ISSUE THREAD

**Issue by Liger333** [Pyratite/pixelcraft#29]
I'm on ios

**Comment by Sh1penfire** [comment]
Not sure what happened there, going to try and figure out why it's missing

**Comment by Liger333** [comment]
also I just want to be clear it appears on pc but on ios the planet select is missing, if it's missing because ios version doesn't support other planets then there's probably nothing wrong with the mod

**Comment by Sh1penfire** [comment]
still no idea what could be causing the second planet loss, sorry.

**Comment by Sh1penfire** [comment]
Could be that mobile dosn't suport scripts, but might have to ask

**Comment by Liger333** [comment]
wait let me check again now

**Comment by Liger333** [comment]
yup still not there

**Comment by LixieWulf** [comment]
iOS does not support Javascript or Java modding.

**Comment by mayo543inator** [comment]
Ios doesnt support js or java modding
