### ISSUE TITLE
Some of your blocks needs resprite 

### ISSUE THREAD

**Issue by DatOnePlayer** [Pyratite/pixelcraft#3]
I mean no hate, I know it is named Pixelcraft but the pixel buildings is kinda an eye sore to see

**Comment by Sh1penfire** [comment]
Sorry about that, I will resprite them when I have the time. Thank you for telling me.

**Comment by DatOnePlayer** [comment]
> Sorry about that, I will resprite them when I have the time. Thank you for telling me.

I'll help when I can, I'm also a former sprinter for a mindustry mod

**Comment by DatOnePlayer** [comment]
@Sh1penfire

**Comment by Sh1penfire** [comment]
oh ok, thank you.

**Comment by Sh1penfire** [comment]
Been working on respriting blocks now
Going to depixelise the shiny beacon, rusted core and fix strand and string sprites and etc
