### ISSUE TITLE
Cannot mine stone

### ISSUE THREAD

**Issue by kapzduke** [Pyratite/pixelcraft#34]
**Describe the bug**
no drill can mine stone, making most of the mod unplayable.

**To Reproduce**
1. enable the mod.

**Expected behavior**
stone should act like a sand tile, that drops stones.

**Screenshots**
![IMG_20210206_165128](https://user-images.githubusercontent.com/60543005/107121635-3519c400-689c-11eb-9544-887d4f351cc4.jpg)

**Info**
pixelcraft v0.9.7
mindustry v123.1

**Additional context**
N/A

- [x] I have checked this issue doesn't already exist.
- [x] This is a bug and not a feature request.

**Comment by Sh1penfire** [comment]
It's fixed now. There was an error in main.js not including the environment script which makes blocks drop stone. If this issue persists, please reinstall the mod, open another issue or contact me directly on discord.
