### ISSUE TITLE
Javelin AI Issue

### ISSUE THREAD

**Issue by JosherIsFun** [Pyratite/pixelcraft#36]
**Describe the bug**
Rusty Javelin AI Broken(Going through defenses and going to core and attack, Ai going to coords, More specifically (0.0))

**To Reproduce**
Use pixelcraft mod
Spawn Rusty Javelin

**Expected behavior**
Acts Like A Flare

**Screenshots**

**Info**
Version of the mod you are running:0.9.7
Version of Mindustry you are running:release 124

**Additional context**

- [x] I have checked this issue doesn't already exist.
- [Yes
![Screenshot_20210209_104235_io anuke mindustry](https://user-images.githubusercontent.com/77379733/107308745-24e42d80-6ac4-11eb-9278-39d6d780a4b6.jpg)
 ] This is a bug and not a feature request.

**Comment by JosherIsFun** [comment]
Help

**Comment by Sh1penfire** [comment]
It might just be running away from you, though I'll see what I can do and if I could fix this behavior/make it act like a flare.
