### ISSUE TITLE
Sinkhole, And Glaciers Spawn Is Buggy

### ISSUE THREAD

**Issue by JosherIsFun** [Pyratite/pixelcraft#37]
**Describe the bug**

**To Reproduce**
1. Go to 'Mod Browser'
2. Click on 'PixelCraft'
3. Go to Sinkhole
4. See Dart Randomly Spawn Without attacking

**Expected behavior** : Attacks/ No Darts Spawn 

**Screenshots**

**Info**
Version of the mod you are running: 0.9.7
Version of Mindustry you are running: Release 124.1
![Screenshot_20210214_132043_io anuke mindustry](https://user-images.githubusercontent.com/77379733/107870868-68310880-6ed7-11eb-8fa0-345a21b70fea.jpg)

- [x] I have checked this issue doesn't already exist.
- [x] This is a bug and not a feature request.

**Comment by JosherIsFun** [comment]
Help Me Again

**Comment by Sh1penfire** [comment]
Unfortunately, the old maps are not able t be updated without losing and manually removing the map file from the game. I am unsure of how to fix this, and this will happen on older builds. I will try and make a custom ai for the darts to lessen the impact of this, but for now use rusty javelins to kill the darts.
