### ISSUE TITLE
Problem with weather on custom game

### ISSUE THREAD

**Issue by mayo543inator** [Pyratite/pixelcraft#41]
**Describe the bug**
Crash when pressing weathers with pixelcraft on
**To Reproduce**
1. Go to 'editor select existing map press rules >weathers crash...'
Haven't checked if this happens always
If make new map weather on weathers tab is gon

I know the cause it's s u n d r y maybe idk

**Comment by Sh1penfire** [comment]
This is something I unfortunately don't know the solution to after awhile of looking and trying to fix the bug. I'll try to fix it when I can and I hope you have a good time.
