### ISSUE TITLE
Blink issues

### ISSUE THREAD

**Issue by ghost** [Pyratite/pixelcraft#42]
**Describe the bug**
It is when you try to enter an 'blink' unit

**To Reproduce**
1. Go to a unit factory set on blink and wait for it to get done
2. Click on the blink until it lets you control it
3. Scroll down to. crash logs said it was from an 'annoymous' unit

**Expected behavior**

**Screenshots**

**Info**
Version of the mod you are running: the test version (0.9.85)
Version of Mindustry you are running: build 126.2

- [x] I have checked this issue doesn't already exist.
- [x] This is a bug and not a feature request.

**Comment by Zeniku** [comment]
@iwantmods82  Please send screenshots of this bug and the CrashLog

**Comment by Sempyos** [comment]
@Zeniku I have same problem what happens is when you tap or hover over a blink unit to see health/shield game freezes and crashes after a few seconds

**Comment by Zeniku** [comment]
Need crash log
