### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vghfr** [Pyratite/pixelcraft#46]
I am making a mod called [Mindustry++](https://github.com/staticalliam7/MindustryPlusPlus) and was curious as to how you made another planet. Your mod is the only one i could find that contained another planet besides Serpulo. Any help will be appreciated!

**Comment by Sh1penfire** [comment]
sorry for the late answer, check Templura.js for planets and sector presets. The generation code should be in extras/templuraGen, though I'll check later. Meanwhile, the waves are found in units/. Hope this helps.

**Comment by vghfr** [comment]
Thanks

**Comment by vghfr** [comment]
Quick question, do you know how to have a block's texture change when it meets a certain parameter?

**Comment by vghfr** [comment]
> Quick question, do you know how to have a block's texture change when it meets a certain parameter?

follow up
