### ISSUE TITLE
Game crashes when going into unnamed levels

### ISSUE THREAD

**Issue by Addedeemus** [Pyratite/pixelcraft#48]
Whenever I try to launch into a new level, it gets stuck on the loading screen and the message "mindustry isn't responding" comes up. This only happens on the modded planet. 

1. Click a nameless level such as 34
2. Tap launch
3. Wait a couple minutes

**Screenshots**
![Screenshot_2021-10-05-13-15-17-753_io anuke mindustry](https://user-images.githubusercontent.com/91950428/136005069-602ed6de-fa8b-4207-b989-cab9bc413a01.jpg)

**Info**
Version of the mod you are running: v.0.9.85
Version of Mindustry you are running: 6-official-126.2

- [x] I have checked this issue doesn't already exist.
- [x] This is a bug and not a feature request.

**Comment by Zeniku** [comment]
Planets are very very unstable rn so it's not a surprise
But if there's a Crashlog then please send it here it is very useful

**Comment by Sh1penfire** [comment]
This will be fixed in due time, it is due to an unoptimized planet generator
