### ISSUE TITLE
Again, unit content errors

### ISSUE THREAD

**Issue by Aweguy** [Pyratite/pixelcraft#6]
There are easily fixed content errors on units right now cuz of the new update. If you allowed me i could push a quick fix for that.

**Comment by Sh1penfire** [comment]
would be appreciated if you could do that, was working on units, never realised that anuke broke the units again...

**Comment by Sh1penfire** [comment]
Sorry about the late reply, I'm probably in a different timezone.

**Comment by Aweguy** [comment]
No problem. I think you saw the suggestion commits. The issue is now closed. Contact me in discord if you want
